/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazAscensor;

import ascensor.Ascensor;
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Olga Lucia
 */
public class InterfazAscensor extends javax.swing.JFrame {

    public InterfazAscensor() {
        initComponents();

        setResizable(false);
        setTitle("Ascensor");
        setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(0, 102, 0));
        setSize(600, 400);
        

    }
    Ascensor ascensor;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Logo = new javax.swing.JLabel();
        jButton_pisoDeServicios = new javax.swing.JButton();
        jButton_crear = new javax.swing.JButton();
        jButton_siguientePiso = new javax.swing.JButton();
        jButton_pisoDeAbajo1 = new javax.swing.JButton();

        jLabel_Logo.setForeground(new java.awt.Color(0, 153, 51));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_pisoDeServicios.setBackground(new java.awt.Color(0, 153, 0));
        jButton_pisoDeServicios.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jButton_pisoDeServicios.setForeground(new java.awt.Color(0, 0, 0));
        jButton_pisoDeServicios.setText("Piso de Servicio");
        jButton_pisoDeServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_pisoDeServiciosActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_pisoDeServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 290, 50));

        jButton_crear.setBackground(new java.awt.Color(0, 153, 0));
        jButton_crear.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jButton_crear.setForeground(new java.awt.Color(0, 0, 0));
        jButton_crear.setText("Crear Ascensor");
        jButton_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_crearActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 290, 50));

        jButton_siguientePiso.setBackground(new java.awt.Color(0, 153, 0));
        jButton_siguientePiso.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jButton_siguientePiso.setForeground(new java.awt.Color(0, 0, 0));
        jButton_siguientePiso.setText("Siguiente Piso");
        jButton_siguientePiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_siguientePisoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_siguientePiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 290, 50));

        jButton_pisoDeAbajo1.setBackground(new java.awt.Color(0, 153, 0));
        jButton_pisoDeAbajo1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jButton_pisoDeAbajo1.setForeground(new java.awt.Color(0, 0, 0));
        jButton_pisoDeAbajo1.setText("Piso de Abajo");
        jButton_pisoDeAbajo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_pisoDeAbajo1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_pisoDeAbajo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 290, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_crearActionPerformed

        int numeroPisos, numeroSotanos;
        JOptionPane.showMessageDialog(null, "A continuacion ingrese los datos para crear el ascensor");
        numeroPisos = Integer.parseInt(JOptionPane.showInputDialog(null, "ingrese numero de pisos"));
        numeroSotanos = Integer.parseInt(JOptionPane.showInputDialog(null, "ingrese numero de sotanos"));
        JOptionPane.showMessageDialog(null, "Acabaste de crear un ascensor para " + numeroPisos
                + " pisos y " + numeroSotanos + " sotanos. ");

        ascensor = new Ascensor(numeroPisos, numeroSotanos);
    }//GEN-LAST:event_jButton_crearActionPerformed

    private void jButton_siguientePisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_siguientePisoActionPerformed
        int pisoActual = Integer.parseInt(JOptionPane.showInputDialog(null, "por favor ingrese el piso actual"));
        if (pisoActual > ascensor.getNumeroPisos() || pisoActual < ascensor.getNumeroSotanos()*-1 ) {
            JOptionPane.showMessageDialog(null, "Lo sentimos, el piso que seleccionaste no existe. Ingresa un piso valido");
        } else {
            ascensor.pisoSiguiente(pisoActual);
        }
    }//GEN-LAST:event_jButton_siguientePisoActionPerformed

    private void jButton_pisoDeAbajo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_pisoDeAbajo1ActionPerformed
        int pisoActual = Integer.parseInt(JOptionPane.showInputDialog(null, "por favor ingrese el piso actual"));
        if (pisoActual > ascensor.getNumeroPisos() || pisoActual < ascensor.getNumeroSotanos()*-1 ) {
            JOptionPane.showMessageDialog(null, "Lo sentimos, el piso que seleccionaste no existe. Ingresa un piso valido");
        } else {
        ascensor.pisoAnterior(pisoActual);
        }
    }//GEN-LAST:event_jButton_pisoDeAbajo1ActionPerformed

    private void jButton_pisoDeServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_pisoDeServiciosActionPerformed
        ascensor.cantidadPisosDeServicio();
    }//GEN-LAST:event_jButton_pisoDeServiciosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazAscensor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazAscensor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazAscensor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazAscensor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazAscensor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_crear;
    private javax.swing.JButton jButton_pisoDeAbajo1;
    private javax.swing.JButton jButton_pisoDeServicios;
    private javax.swing.JButton jButton_siguientePiso;
    private javax.swing.JLabel jLabel_Logo;
    // End of variables declaration//GEN-END:variables
}
